FROM golang:1.21

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENV PORT=8081
ENV SECRET_KEY=myKey

COPY . .

ENV MONGO_URI=mongodb://root:psw@localhost:27017/users?connect=direct&authSource=admin
CMD ["go", "test", "./..."]