<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class KubecampProgressModelsProgressHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="date") */
        if (isset($data['completionDate'])) {
            $value = $data['completionDate'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['completionDate']->setValue($document, clone $return);
            $hydratedData['completionDate'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['lessonId']) || (! empty($this->class->fieldMappings['lessonId']['nullable']) && array_key_exists('lessonId', $data))) {
            $value = $data['lessonId'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['lessonId']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['lessonId']->setValue($document, $return);
            $hydratedData['lessonId'] = $return;
        }
        return $hydratedData;
    }
}