version: "3"
services:
  go-auth:
    build:
      context: ./go-auth
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./go-auth:/app
    environment:
      MONGO_URI: "mongodb://db-auth-mongo:27017/users?connect=direct&authSource=admin"
      PORT: 8080
      SECRET_KEY: pJmJmc4qnEX8/cG/h47zj++9CsFCJY2sda44oFu/USyB6ONEyUO8rg2VdiyvDPYw
    depends_on:
      - db-auth-mongo
  db-auth-mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db-auth-mongo-data:/data/db
      - ./go-auth/mongo-init:/docker-entrypoint-initdb.d
  java-catalog:
    build:
      context: ./java-catalog
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-catalog-postgres:5432/kubecamp_catalog
      - SPRING_DATASOURCE_USERNAME=kubecamp
      - SPRING_DATASOURCE_PASSWORD=kubecamp
      - SPRING_JPA_HIBERNATE_JDBC_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081
    volumes:
      - ./java-catalog:/app
    depends_on:
      - db-catalog-postgres
      - go-auth
  db-catalog-postgres:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=kubecamp
      - POSTGRES_PASSWORD=kubecamp
      - POSTGRES_DB=kubecamp_catalog
    volumes:
      - db-catalog-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  php-progress:
    build:
      context: ./php-progress
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./php-progress:/var/www/html
    ports:
      - 9000:9000
    environment:
      MONGODB_HOST: db-progress-mongo
      MONGODB_PORT: 27017
    depends_on:
      - db-progress-mongo
      - go-auth
  php-nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./php-progress/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-progress
  db-progress-mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db-progress-mongo-data:/data/db
  python-discuss:
    build:
      context: ./python-discuss
      dockerfile: ./Dockerfile
    restart: unless-stopped
    # volumes:
      # - ./python-discuss:/app
    ports:
      - 8083:8083
    environment:
      MONGODB_HOST: db-discuss-mongo
      MONGODB_PORT: 27017
      MONGODB_DB: kubecampDiscussion
      PORT: 8083
      AUTH_SERVICE_URL: http://go-auth:8080
    depends_on:
      - db-discuss-mongo
      - go-auth
  db-discuss-mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - db-discuss-mongo-data:/data/db
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-auth
      - java-catalog
      - php-nginx
      - python-discuss
volumes:
  db-catalog-postgres-data:
  db-auth-mongo-data:
  db-progress-mongo-data:
  db-discuss-mongo-data:
