apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.go_auth.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.go_auth.port }}  # Utiliza el valor definido en values.yaml para go-auth
      targetPort: http
      protocol: TCP
      name: http
  containers:
  - name: go_auth
    image: {{ .Values.go_auth.image }}
