apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.php_progress.name }}
  labels:
    {{- include "project-kubecamp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.php_progress.port }}  
      targetPort: http
      protocol: TCP
      name: http
  containers:
  - name: php_progress
    image: {{ .Values.php_progress.image }}
  selector:
    {{- include "project-kubecamp.selectorLabels" . | nindent 4 }}