apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.php_progress.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.php_progress.port }}  
      targetPort: http
      protocol: TCP
      name: http
  containers:
  - name: php_progress
    image: {{ .Values.php_progress.image }}