version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    tty: true
    volumes:
      - .:/app
    ports:
      - 8081:5000
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: kubecampDiscussion
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
