apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.python_discuss.name }}
  labels:
    {{ include "project-kubecamp.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.python_discuss.port }}  
      targetPort: http
      protocol: TCP
      name: http
  containers:
    - name: python_discuss
      image: {{ .Values.python_discuss.image }}
  selector:
    {{ include "project-kubecamp.selectorLabels" . }}